apiVersion: v1
kind: Service
metadata:
  name: hello-docker-app-service
spec:
  type: NodePort
  selector:
    app: hello-docker-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
